run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  depguard:
    packages:
      - "github.com/nicksnyder/go-i18n/v2/i18n"
    packages-with-error-message:
      - github.com/nicksnyder/go-i18n/v2/i18n: "use mattermost/mattermost-plugin-api/i18n instead"
  forbidigo:
    forbid:
      - ^.*\.MustLocalize.*$
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/matterpoll/matterpoll
  golint:
    min-confidence: 0.0
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
